namespace AwesomeExcel.Common.Models;

/// <summary>
/// Enumeration of colors
/// </summary>
public enum Color : short
{
    // Check https://github.com/ClosedXML/ClosedXML/wiki/Excel-Indexed-Colors for colors

    //Black = 0,
    //White = 1,
    //Red = 2,
    //BrightGreen = 3,
    //Blue = 4,
    //Yellow = 5,
    //Pink = 6,
    //Turquoise = 7,
    Black = 8,
    White = 9,
    Red = 10,
    BrightGreen = 11,
    Blue = 12,
    Yellow = 13,
    Pink = 14,
    Turquoise = 15,
    DarkRed = 16,
    Green = 17,
    DarkBlue = 18,
    DarkYellow = 19,
    Violet = 20,
    Teal = 21,
    Gray_25Percent = 22,
    Gray_50Percent = 23,
    Periwinkle = 24,
    Plum = 25,
    Ivory = 26,
    LightTurquoise = 27,
    DarkPurple = 28,
    Coral = 29,
    OceanBlue = 30,
    IceBlue = 31,
    //DarkBlue = 32,
    //Pink = 33,
    //Yellow = 34,
    //Turquoise = 35,
    //Violet = 36,
    //DarkRed = 37,
    //Teal = 38,
    //Blue = 39,
    SkyBlue = 40,
    //LightTurquoise = 41,
    LightGreen = 42,
    LightYellow = 43,
    PaleBlue = 44,
    Rose = 45,
    Lavender = 46,
    Tan = 47,
    LightBlue = 48,
    Aqua = 49,
    Lime = 50,
    Gold = 51,
    LightOrange = 52,
    Orange = 53,
    BlueGray = 54,
    Gray_40Percent = 55,
    DarkTeal = 56,
    SeaGreen = 57,
    DarkGreen = 58,
    OliveGreen = 59,
    Brown = 60,
    //Plum = 61,
    Indigo = 62,
    Gray_80Percent = 63,
}
